---
AWSTemplateFormatVersion: "2010-09-09"
Description: This stack deploys a Secret containing credentials for Snowpipe Streaming

Parameters:
  SnowflakeAccountUrl:
    Type: String
    Description: Snowflake account URL

  SnowflakeUser:
    Type: String
    Description: Username for the Snowflake account 

  SnowflakePrivateKey:
    Type: String
    Description: Private key for the Snowflake account
    NoEcho: true
    MinLength: 5
    
  SnowflakeRole:
    Type: String
    Description: Snowflake role to use

Resources:
# Secret Manager
  SnowflakeSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub ${AWS::StackName}-SnowflakeSecret
      Description: This secret has the credentials for the Snowflake account
      SecretString:
        !Join
          - '' 
          - - '{"url":"'
            - !Ref SnowflakeAccountUrl
            - '","user":"'
            - !Ref SnowflakeUser
            - '", "private_key":"'
            - !Ref SnowflakePrivateKey
            - '", "role":"'
            - !Ref SnowflakeRole
            - '"}'


Outputs:
  SnowpipeSecret:
    Value: !Sub ${AWS::StackName}-SnowflakeSecret
  SnowflakeSecretArn:
    Value: !Ref SnowflakeSecret
